/**
 * Sticker catalogue for the diary.
 *
 * Emoji rather than image assets: they render at any size without a network
 * request, work in both themes, and there are enough of them to fill a proper
 * scrapbook tray. Grouped so the picker can offer tabs, and every sticker
 * carries keywords so search finds things by feeling as well as by name.
 */

export interface StickerCategory {
  id: string;
  label: string;
  /** Shown on the category tab. */
  icon: string;
  stickers: { emoji: string; name: string }[];
}

export const STICKER_CATEGORIES: StickerCategory[] = [
  {
    id: 'moods',
    label: 'Moods',
    icon: '😊',
    stickers: [
      { emoji: '😊', name: 'happy' },
      { emoji: '🥰', name: 'loved adore' },
      { emoji: '😍', name: 'heart eyes' },
      { emoji: '🤗', name: 'hug' },
      { emoji: '😌', name: 'calm relieved' },
      { emoji: '😴', name: 'sleepy tired' },
      { emoji: '🤔', name: 'thinking' },
      { emoji: '😅', name: 'nervous laugh' },
      { emoji: '😂', name: 'laughing' },
      { emoji: '🙃', name: 'silly upside down' },
      { emoji: '😎', name: 'cool' },
      { emoji: '🥳', name: 'party celebrate' },
      { emoji: '😢', name: 'sad cry' },
      { emoji: '😭', name: 'sobbing' },
      { emoji: '😰', name: 'anxious worried' },
      { emoji: '😤', name: 'frustrated' },
      { emoji: '😡', name: 'angry mad' },
      { emoji: '🥺', name: 'pleading' },
      { emoji: '😔', name: 'down low' },
      { emoji: '🫠', name: 'melting overwhelmed' },
      { emoji: '😶‍🌫️', name: 'foggy numb' },
      { emoji: '🤯', name: 'mind blown' },
      { emoji: '🥱', name: 'yawn bored' },
      { emoji: '😇', name: 'innocent' },
    ],
  },
  {
    id: 'hearts',
    label: 'Hearts',
    icon: '❤️',
    stickers: [
      { emoji: '❤️', name: 'red heart love' },
      { emoji: '🧡', name: 'orange heart' },
      { emoji: '💛', name: 'yellow heart' },
      { emoji: '💚', name: 'green heart' },
      { emoji: '💙', name: 'blue heart' },
      { emoji: '💜', name: 'purple heart' },
      { emoji: '🖤', name: 'black heart' },
      { emoji: '🤍', name: 'white heart' },
      { emoji: '🤎', name: 'brown heart' },
      { emoji: '💗', name: 'growing heart' },
      { emoji: '💖', name: 'sparkling heart' },
      { emoji: '💘', name: 'heart arrow' },
      { emoji: '💝', name: 'heart gift' },
      { emoji: '💞', name: 'revolving hearts' },
      { emoji: '💕', name: 'two hearts' },
      { emoji: '💓', name: 'beating heart' },
      { emoji: '💔', name: 'broken heart' },
      { emoji: '❣️', name: 'heart exclamation' },
      { emoji: '✨', name: 'sparkles' },
      { emoji: '💫', name: 'dizzy star' },
      { emoji: '⭐', name: 'star' },
      { emoji: '🌟', name: 'glowing star' },
      { emoji: '🔥', name: 'fire hot' },
      { emoji: '💥', name: 'boom' },
    ],
  },
  {
    id: 'weather',
    label: 'Weather',
    icon: '☀️',
    stickers: [
      { emoji: '☀️', name: 'sun sunny' },
      { emoji: '🌤️', name: 'partly sunny' },
      { emoji: '⛅', name: 'cloudy sun' },
      { emoji: '☁️', name: 'cloud' },
      { emoji: '🌧️', name: 'rain' },
      { emoji: '⛈️', name: 'storm thunder' },
      { emoji: '🌩️', name: 'lightning' },
      { emoji: '❄️', name: 'snow cold' },
      { emoji: '☃️', name: 'snowman' },
      { emoji: '🌨️', name: 'snowing' },
      { emoji: '🌈', name: 'rainbow' },
      { emoji: '🌪️', name: 'tornado' },
      { emoji: '🌫️', name: 'fog mist' },
      { emoji: '🌙', name: 'moon night' },
      { emoji: '🌛', name: 'moon face' },
      { emoji: '🌝', name: 'full moon' },
      { emoji: '🌅', name: 'sunrise' },
      { emoji: '🌇', name: 'sunset' },
      { emoji: '🌊', name: 'wave ocean' },
      { emoji: '💧', name: 'droplet' },
    ],
  },
  {
    id: 'plants',
    label: 'Plants',
    icon: '🌸',
    stickers: [
      { emoji: '🌸', name: 'cherry blossom' },
      { emoji: '🌷', name: 'tulip' },
      { emoji: '🌹', name: 'rose' },
      { emoji: '🌺', name: 'hibiscus' },
      { emoji: '🌻', name: 'sunflower' },
      { emoji: '🌼', name: 'daisy' },
      { emoji: '💐', name: 'bouquet' },
      { emoji: '🪷', name: 'lotus' },
      { emoji: '🌱', name: 'seedling grow' },
      { emoji: '🌿', name: 'herb leaves' },
      { emoji: '🍀', name: 'clover lucky' },
      { emoji: '🍃', name: 'leaves wind' },
      { emoji: '🍁', name: 'maple autumn' },
      { emoji: '🍂', name: 'fallen leaves' },
      { emoji: '🌳', name: 'tree' },
      { emoji: '🌲', name: 'evergreen' },
      { emoji: '🌵', name: 'cactus' },
      { emoji: '🪴', name: 'potted plant' },
      { emoji: '🍄', name: 'mushroom' },
      { emoji: '🌾', name: 'wheat' },
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    icon: '🐱',
    stickers: [
      { emoji: '🐱', name: 'cat' },
      { emoji: '🐶', name: 'dog' },
      { emoji: '🐰', name: 'rabbit bunny' },
      { emoji: '🐻', name: 'bear' },
      { emoji: '🐼', name: 'panda' },
      { emoji: '🐨', name: 'koala' },
      { emoji: '🦊', name: 'fox' },
      { emoji: '🐯', name: 'tiger' },
      { emoji: '🦁', name: 'lion' },
      { emoji: '🐮', name: 'cow' },
      { emoji: '🐷', name: 'pig' },
      { emoji: '🐸', name: 'frog' },
      { emoji: '🐵', name: 'monkey' },
      { emoji: '🐧', name: 'penguin' },
      { emoji: '🐦', name: 'bird' },
      { emoji: '🦋', name: 'butterfly' },
      { emoji: '🐝', name: 'bee' },
      { emoji: '🐞', name: 'ladybug' },
      { emoji: '🐢', name: 'turtle' },
      { emoji: '🐙', name: 'octopus' },
      { emoji: '🐳', name: 'whale' },
      { emoji: '🐬', name: 'dolphin' },
      { emoji: '🦄', name: 'unicorn' },
      { emoji: '🐴', name: 'horse' },
      { emoji: '🦉', name: 'owl' },
      { emoji: '🦔', name: 'hedgehog' },
      { emoji: '🐑', name: 'sheep' },
      { emoji: '🐈‍⬛', name: 'black cat' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '☕',
    stickers: [
      { emoji: '☕', name: 'coffee' },
      { emoji: '🍵', name: 'tea' },
      { emoji: '🧋', name: 'boba bubble tea' },
      { emoji: '🥤', name: 'soda drink' },
      { emoji: '🍰', name: 'cake slice' },
      { emoji: '🎂', name: 'birthday cake' },
      { emoji: '🧁', name: 'cupcake' },
      { emoji: '🍪', name: 'cookie' },
      { emoji: '🍩', name: 'donut' },
      { emoji: '🍫', name: 'chocolate' },
      { emoji: '🍬', name: 'candy' },
      { emoji: '🍭', name: 'lollipop' },
      { emoji: '🍦', name: 'ice cream' },
      { emoji: '🍓', name: 'strawberry' },
      { emoji: '🍒', name: 'cherries' },
      { emoji: '🍑', name: 'peach' },
      { emoji: '🍊', name: 'orange' },
      { emoji: '🍋', name: 'lemon' },
      { emoji: '🍉', name: 'watermelon' },
      { emoji: '🍇', name: 'grapes' },
      { emoji: '🥑', name: 'avocado' },
      { emoji: '🍕', name: 'pizza' },
      { emoji: '🍜', name: 'noodles ramen' },
      { emoji: '🍣', name: 'sushi' },
      { emoji: '🥐', name: 'croissant' },
      { emoji: '🥞', name: 'pancakes' },
      { emoji: '🍿', name: 'popcorn' },
      { emoji: '🍯', name: 'honey' },
    ],
  },
  {
    id: 'activities',
    label: 'Doing',
    icon: '📚',
    stickers: [
      { emoji: '📚', name: 'books reading' },
      { emoji: '📖', name: 'open book' },
      { emoji: '✏️', name: 'pencil write' },
      { emoji: '🖊️', name: 'pen' },
      { emoji: '🖌️', name: 'paintbrush' },
      { emoji: '🎨', name: 'art palette' },
      { emoji: '🎵', name: 'music note' },
      { emoji: '🎧', name: 'headphones' },
      { emoji: '🎸', name: 'guitar' },
      { emoji: '🎹', name: 'piano' },
      { emoji: '🎬', name: 'movie film' },
      { emoji: '🎮', name: 'gaming' },
      { emoji: '🧩', name: 'puzzle' },
      { emoji: '🏃', name: 'running' },
      { emoji: '🧘', name: 'yoga meditate' },
      { emoji: '🚴', name: 'cycling' },
      { emoji: '🏊', name: 'swimming' },
      { emoji: '⚽', name: 'football soccer' },
      { emoji: '🏀', name: 'basketball' },
      { emoji: '🧶', name: 'yarn knitting' },
      { emoji: '📷', name: 'camera photo' },
      { emoji: '💻', name: 'laptop work' },
      { emoji: '🛌', name: 'rest sleep' },
      { emoji: '🛁', name: 'bath' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    icon: '✈️',
    stickers: [
      { emoji: '✈️', name: 'plane flight' },
      { emoji: '🚗', name: 'car drive' },
      { emoji: '🚂', name: 'train' },
      { emoji: '🚲', name: 'bicycle' },
      { emoji: '⛵', name: 'sailboat' },
      { emoji: '🏝️', name: 'island beach' },
      { emoji: '🏔️', name: 'mountain' },
      { emoji: '🏕️', name: 'camping' },
      { emoji: '🗺️', name: 'map' },
      { emoji: '🧳', name: 'luggage' },
      { emoji: '🎡', name: 'ferris wheel' },
      { emoji: '🗼', name: 'tower' },
      { emoji: '🌍', name: 'earth world' },
      { emoji: '📍', name: 'location pin' },
      { emoji: '🏠', name: 'home house' },
      { emoji: '🏨', name: 'hotel' },
      { emoji: '🎪', name: 'circus tent' },
      { emoji: '🌉', name: 'bridge' },
      { emoji: '🚀', name: 'rocket' },
      { emoji: '🎒', name: 'backpack' },
    ],
  },
  {
    id: 'stationery',
    label: 'Desk',
    icon: '📌',
    stickers: [
      { emoji: '📌', name: 'pin' },
      { emoji: '📎', name: 'paperclip' },
      { emoji: '✂️', name: 'scissors' },
      { emoji: '📏', name: 'ruler' },
      { emoji: '🗒️', name: 'notepad' },
      { emoji: '📝', name: 'memo note' },
      { emoji: '📔', name: 'notebook' },
      { emoji: '📒', name: 'ledger' },
      { emoji: '🔖', name: 'bookmark' },
      { emoji: '🏷️', name: 'label tag' },
      { emoji: '💌', name: 'love letter' },
      { emoji: '✉️', name: 'envelope' },
      { emoji: '📬', name: 'mailbox' },
      { emoji: '🗓️', name: 'calendar' },
      { emoji: '⏰', name: 'alarm clock' },
      { emoji: '⌛', name: 'hourglass' },
      { emoji: '🔑', name: 'key' },
      { emoji: '🕯️', name: 'candle' },
      { emoji: '🔍', name: 'magnifier search' },
      { emoji: '🧷', name: 'safety pin' },
      { emoji: '📐', name: 'set square' },
      { emoji: '🖇️', name: 'linked clips' },
      { emoji: '🗂️', name: 'dividers' },
      { emoji: '📤', name: 'outbox' },
    ],
  },
  {
    id: 'celebrate',
    label: 'Special',
    icon: '🎁',
    stickers: [
      { emoji: '🎁', name: 'gift present' },
      { emoji: '🎉', name: 'party popper' },
      { emoji: '🎊', name: 'confetti' },
      { emoji: '🎈', name: 'balloon' },
      { emoji: '🏆', name: 'trophy win' },
      { emoji: '🥇', name: 'gold medal' },
      { emoji: '👑', name: 'crown' },
      { emoji: '💎', name: 'gem diamond' },
      { emoji: '🪄', name: 'magic wand' },
      { emoji: '🧸', name: 'teddy bear' },
      { emoji: '🎀', name: 'ribbon bow' },
      { emoji: '🍾', name: 'champagne' },
      { emoji: '🥂', name: 'cheers toast' },
      { emoji: '🎆', name: 'fireworks' },
      { emoji: '🪅', name: 'pinata' },
      { emoji: '🎃', name: 'pumpkin' },
      { emoji: '🎄', name: 'christmas tree' },
      { emoji: '🕊️', name: 'dove peace' },
      { emoji: '🫶', name: 'heart hands' },
      { emoji: '🙌', name: 'celebrate hands' },
    ],
  },
  {
    id: 'symbols',
    label: 'Marks',
    icon: '✅',
    stickers: [
      { emoji: '✅', name: 'check done' },
      { emoji: '❌', name: 'cross no' },
      { emoji: '❗', name: 'exclamation' },
      { emoji: '❓', name: 'question' },
      { emoji: '💡', name: 'idea lightbulb' },
      { emoji: '⚡', name: 'lightning energy' },
      { emoji: '🎯', name: 'target goal' },
      { emoji: '🚩', name: 'flag' },
      { emoji: '⚠️', name: 'warning' },
      { emoji: '♻️', name: 'recycle' },
      { emoji: '🔒', name: 'locked' },
      { emoji: '🔔', name: 'bell reminder' },
      { emoji: '💤', name: 'sleeping zzz' },
      { emoji: '💭', name: 'thought bubble' },
      { emoji: '💬', name: 'speech bubble' },
      { emoji: '👀', name: 'eyes look' },
      { emoji: '👍', name: 'thumbs up' },
      { emoji: '👎', name: 'thumbs down' },
      { emoji: '🤞', name: 'fingers crossed' },
      { emoji: '💪', name: 'strong' },
    ],
  },
];

/** Flat list, for search across every category. */
export const ALL_STICKERS = STICKER_CATEGORIES.flatMap((c) =>
  c.stickers.map((s) => ({ ...s, category: c.id }))
);

export const stickerMatches = (
  sticker: { emoji: string; name: string },
  query: string
): boolean => {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return sticker.name.toLowerCase().includes(q) || sticker.emoji === q;
};
